/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx}', './public/index.html'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-deep': '#0A0A14',
        'surface-raised': '#0F0F1A',
        'surface': '#111317',
        'surface-dim': '#111317',
        'surface-bright': '#37393d',
        'surface-container-lowest': '#0c0e12',
        'surface-container-low': '#1a1c1f',
        'surface-container': '#1e2023',
        'surface-container-high': '#282a2e',
        'surface-container-highest': '#333539',
        'surface-variant': '#333539',
        'on-surface': '#e2e2e7',
        'on-surface-variant': '#c8c4d7',
        'inverse-surface': '#e2e2e7',
        'inverse-on-surface': '#2e3034',
        'outline': '#928ea0',
        'outline-variant': '#474554',
        'surface-tint': '#c6bfff',
        'primary': '#c6bfff',
        'on-primary': '#2900a0',
        'primary-container': '#6c5ce7',
        'on-primary-container': '#faf6ff',
        'inverse-primary': '#5847d2',
        'primary-fixed': '#e4dfff',
        'primary-fixed-dim': '#c6bfff',
        'on-primary-fixed': '#160066',
        'on-primary-fixed-variant': '#4029ba',
        'secondary': '#a6e6ff',
        'on-secondary': '#003543',
        'secondary-container': '#14d1ff',
        'on-secondary-container': '#00566b',
        'secondary-fixed': '#b7eaff',
        'secondary-fixed-dim': '#4cd6ff',
        'on-secondary-fixed': '#001f28',
        'on-secondary-fixed-variant': '#004e60',
        'tertiary': '#ffb77d',
        'on-tertiary': '#4d2600',
        'tertiary-container': '#ac5d00',
        'on-tertiary-container': '#fff5f1',
        'tertiary-fixed': '#ffdcc3',
        'tertiary-fixed-dim': '#ffb77d',
        'on-tertiary-fixed': '#2f1500',
        'on-tertiary-fixed-variant': '#6e3900',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'background': '#111317',
        'on-background': '#e2e2e7',
        'accent-electric': '#00D1FF',
        'accent-neon-purple': '#A29BFE',
        'text-muted': '#8888AA',
      },
      fontFamily: {
        'display-lg': ['IBM Plex Sans Arabic', 'sans-serif'],
        'display-lg-mobile': ['IBM Plex Sans Arabic', 'sans-serif'],
        'headline-md': ['IBM Plex Sans Arabic', 'sans-serif'],
        'headline-sm': ['IBM Plex Sans Arabic', 'sans-serif'],
        'body-lg': ['IBM Plex Sans Arabic', 'sans-serif'],
        'body-md': ['IBM Plex Sans Arabic', 'sans-serif'],
        'label-caps': ['Space Grotesk', 'sans-serif'],
        'price-tag': ['Space Grotesk', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '60px', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '44px', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-caps': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'price-tag': ['20px', { lineHeight: '24px', fontWeight: '700' }],
      },
      spacing: {
        'margin-edge': '32px',
        'gutter': '24px',
        'section-gap': '80px',
        'container-max': '1280px',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '9999px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
};
